package com.khuongtest.model;
// Generated Jan 19, 2017 3:15:39 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FooddetailsId generated by hbm2java
 */
@Embeddable
public class FooddetailsId implements java.io.Serializable {

	private int foodIdfood;
	private int restaurantIdrestaurant;

	public FooddetailsId() {
	}

	public FooddetailsId(int foodIdfood, int restaurantIdrestaurant) {
		this.foodIdfood = foodIdfood;
		this.restaurantIdrestaurant = restaurantIdrestaurant;
	}

	@Column(name = "Food_idfood", nullable = false)
	public int getFoodIdfood() {
		return this.foodIdfood;
	}

	public void setFoodIdfood(int foodIdfood) {
		this.foodIdfood = foodIdfood;
	}

	@Column(name = "Restaurant_idrestaurant", nullable = false)
	public int getRestaurantIdrestaurant() {
		return this.restaurantIdrestaurant;
	}

	public void setRestaurantIdrestaurant(int restaurantIdrestaurant) {
		this.restaurantIdrestaurant = restaurantIdrestaurant;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FooddetailsId))
			return false;
		FooddetailsId castOther = (FooddetailsId) other;

		return (this.getFoodIdfood() == castOther.getFoodIdfood())
				&& (this.getRestaurantIdrestaurant() == castOther.getRestaurantIdrestaurant());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFoodIdfood();
		result = 37 * result + this.getRestaurantIdrestaurant();
		return result;
	}

}
