package com.khuongtest.model;
// Generated Jan 19, 2017 3:15:39 PM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fooddetails generated by hbm2java
 */
@Entity
@Table(name = "fooddetails", catalog = "usvnrestaurants")
public class Fooddetails implements java.io.Serializable {

	private FooddetailsId id;
	private Food food;
	private Restaurant restaurant;
	private String price;
	private String ratingpoint;
	private Integer status;
	private Set<Rate> rates = new HashSet<Rate>(0);

	public Fooddetails() {
	}

	public Fooddetails(FooddetailsId id, Food food, Restaurant restaurant) {
		this.id = id;
		this.food = food;
		this.restaurant = restaurant;
	}

	public Fooddetails(FooddetailsId id, Food food, Restaurant restaurant, String price, String ratingpoint,
			Integer status, Set<Rate> rates) {
		this.id = id;
		this.food = food;
		this.restaurant = restaurant;
		this.price = price;
		this.ratingpoint = ratingpoint;
		this.status = status;
		this.rates = rates;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "foodIdfood", column = @Column(name = "Food_idfood", nullable = false)),
			@AttributeOverride(name = "restaurantIdrestaurant", column = @Column(name = "Restaurant_idrestaurant", nullable = false)) })
	public FooddetailsId getId() {
		return this.id;
	}

	public void setId(FooddetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Food_idfood", nullable = false, insertable = false, updatable = false)
	public Food getFood() {
		return this.food;
	}

	public void setFood(Food food) {
		this.food = food;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Restaurant_idrestaurant", nullable = false, insertable = false, updatable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@Column(name = "price", length = 10)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "ratingpoint", length = 5)
	public String getRatingpoint() {
		return this.ratingpoint;
	}

	public void setRatingpoint(String ratingpoint) {
		this.ratingpoint = ratingpoint;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fooddetails")
	public Set<Rate> getRates() {
		return this.rates;
	}

	public void setRates(Set<Rate> rates) {
		this.rates = rates;
	}

}
