package com.khuongtest.model;
// Generated Jan 17, 2017 4:41:58 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rate generated by hbm2java
 */
@Entity
@Table(name = "rate", catalog = "usvnrestaurants")
public class Rate implements java.io.Serializable {

	private Integer idRate;
	private Account account;
	private Fooddetails fooddetails;
	private Integer point;

	public Rate() {
	}

	public Rate(Account account, Fooddetails fooddetails) {
		this.account = account;
		this.fooddetails = fooddetails;
	}

	public Rate(Account account, Fooddetails fooddetails, Integer point) {
		this.account = account;
		this.fooddetails = fooddetails;
		this.point = point;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idRate", unique = true, nullable = false)
	public Integer getIdRate() {
		return this.idRate;
	}

	public void setIdRate(Integer idRate) {
		this.idRate = idRate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Account_idAccount", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "FoodDetails_Food_idfood", referencedColumnName = "Food_idfood", nullable = false),
			@JoinColumn(name = "FoodDetails_Restaurant_idrestaurant", referencedColumnName = "Restaurant_idrestaurant", nullable = false) })
	public Fooddetails getFooddetails() {
		return this.fooddetails;
	}

	public void setFooddetails(Fooddetails fooddetails) {
		this.fooddetails = fooddetails;
	}

	@Column(name = "point")
	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

}
