package com.khuongtest.model;
// Generated Jan 17, 2017 4:41:58 PM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Restaurant generated by hbm2java
 */
@Entity
@Table(name = "restaurant", catalog = "usvnrestaurants")
public class Restaurant implements java.io.Serializable {

	private Integer idrestaurant;
	private String name;
	private String address;
	private String latitude;
	private String longitude;
	private String description;
	private String imageUrl;
	private Set<Fooddetails> fooddetailses = new HashSet<Fooddetails>(0);

	public Restaurant() {
	}

	public Restaurant(String name, String address, String latitude, String longitude, String description,
			String imageUrl, Set<Fooddetails> fooddetailses) {
		this.name = name;
		this.address = address;
		this.latitude = latitude;
		this.longitude = longitude;
		this.description = description;
		this.imageUrl = imageUrl;
		this.fooddetailses = fooddetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idrestaurant", unique = true, nullable = false)
	public Integer getIdrestaurant() {
		return this.idrestaurant;
	}

	public void setIdrestaurant(Integer idrestaurant) {
		this.idrestaurant = idrestaurant;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "latitude", length = 45)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", length = 45)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "imageURL", length = 100)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Fooddetails> getFooddetailses() {
		return this.fooddetailses;
	}

	public void setFooddetailses(Set<Fooddetails> fooddetailses) {
		this.fooddetailses = fooddetailses;
	}

}
